### ISSUE TITLE
Missing Encryption Feature

### ISSUE THREAD

**Issue by super3** [Storj/metatool#15]
Metatool supports decryption, but not encryption.  Looks like this was missed. Please see the MetaDisk 2.5 spec for the encryption library we want to use.

**Comment by super3** [comment]
@ViktorovEugene Looks to be the last thing that needs to be done. Let me know the ETA on this.

**Comment by ViktorovEugene** [comment]
I've already resolved the problem, but I can't make up one's mind, how to save decryption key. I assume, that it should be the file with decryption key as the content and the "hash_name_value.decryptionkey" as name of the file.
So, can you tell me:
- How to save decryption key?
- Is just generated decryption key should be printed to screen, while uploading with encryption?
- Is decryption key should be passed to CLI as --decryption_key "KEY_VALUE" optional argument, or may be as the file? Or, even, the both variants need to be available?

**Comment by ViktorovEugene** [comment]
You can try the encryption now. 
`metatool upload big_file.zip --encrypt`

**Comment by super3** [comment]
I think the decryption key should be added to the output up the upload command. 

```
$ metatool upload README.md 
201
{
  "data_hash": "fcd533cd12aa8a9e9ffc7ee0f53198cf76da551e211aff85d2a2ef35639f99e9",
  "decryption_key": "123456",
  "file_role": "001"
}
```

This will require adding the decryption key as an element in the JSON after receiving a response back from MetaDisk. 

On download MetaDisk should never pass the decryption key to the server unless the `--link` command is passed. It should always encrypt and decrypt the file on the client side.

**Comment by ViktorovEugene** [comment]
I'm thinking, that "metacore" has a wrong logic now, - if the invalid decryption key is passed, **500 Internal Server Error** response will be returned in the Debug=False mode. There is no instructions in the MetaCore specification for this case. What is your thought about this?

**Comment by super3** [comment]
@ViktorovEugene What are you classifying as an invalid decryption key? Ideally we don't want someone to try to brute force decryption by trying common passphrases. Furthermore we might want to support multiple encryption schemes which might have different bit lengths, etc.

**Comment by ViktorovEugene** [comment]
For example, if I will lose the last character, whilst copy-pasting an URL string, returned from the "download ... --link" command?

**Comment by super3** [comment]
What will the decryption library output if that happens?

**Comment by ViktorovEugene** [comment]
If there are directly missing the part of string, which represents a single byte:

```
>>> file_encryptor.convergence.decrypt_file_inline('test.txt', key[:-1])
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/file_encryptor/convergence.py", line 65, in decrypt_file_inline
    inline_transform(filename, key)
  File "build/bdist.linux-x86_64/egg/file_encryptor/convergence.py", line 98, in inline_transform
    for chunk, fp in iter_transform(filename, key):
  File "build/bdist.linux-x86_64/egg/file_encryptor/convergence.py", line 120, in iter_transform
    aes = AES.new(key, AES.MODE_CTR, counter=Counter.new(128))
  File "build/bdist.linux-x86_64/egg/Crypto/Cipher/AES.py", line 95, in new
    return AESCipher(key, *args, **kwargs)
  File "build/bdist.linux-x86_64/egg/Crypto/Cipher/AES.py", line 59, in __init__
    blockalgo.BlockAlgo.__init__(self, _AES, key, *args, **kwargs)
  File "build/bdist.linux-x86_64/egg/Crypto/Cipher/blockalgo.py", line 141, in __init__
    self._cipher = factory.new(key, *args, **kwargs)
ValueError: AES key must be either 16, 24, or 32 bytes long
```

but, there are some cases, when incomplete URL string, can be interpreted as the full 32 bytes long value, but distorted one. For example the original, valid URL query is - 

> http://localhost:5000/api/files/0c50ca846cba1140c1d1be3bdd1f9c10efed6e2692889e8520c73b96a548e998?decryption_key=%255B%25FCX%2595.%25FA%2586%25A8%259A%25B8%259C%25F6%25B6%2505%25C9%25B8%25BF%25CD%2508%25D9%25B4N%2560p%25E7ai%251C%25A1%25ED%252BW

It will be interpreted as acceptable **decryption_key**, if we will cut the last two characters `BW` .
So, it will be the next:

> [\xfcX\x95.\xfa\x86\xa8\x9a\xb8\x9c\xf6\xb6\x05\xc9\xb8\xbf\xcd\x08\xd9\xb4N`p\xe7ai\x1c\xa1\xed%2

instead of the original value: 

> [\xfcX\x95.\xfa\x86\xa8\x9a\xb8\x9c\xf6\xb6\x05\xc9\xb8\xbf\xcd\x08\xd9\xb4N`p\xe7ai\x1c\xa1\xed+W

As a result, if we copy whole string, we will have correcrly downloaded, decrypted file,
but, if we've messed the string, there are two available bugs:
- Error because of wrong lengh of the AES key.
- Download the lame-decrypted file.

**Comment by super3** [comment]
Ok. I think it would make sense to define an error code for when you use
the wrong bitlength for a key or do something else wrong with the key for
any encryption algorithm. Should be general purpose, not just for AES.

Shawn.
